Add required dependencies.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,77 @@
-#!/bin/sh
+#!/bin/bash
 
+# Check if messages are to be printed using color.
+unset ALL_OFF BOLD BLUE GREEN RED YELLOW
+
+if [[ -t 2 ]]; then
+	# Prefer terminal safe colored and bold text when tput is supported.
+	if tput setaf 0 &>/dev/null; then
+		ALL_OFF="$(tput sgr0)"
+		BOLD="$(tput bold)"
+		BLUE="${BOLD}$(tput setaf 4)"
+		GREEN="${BOLD}$(tput setaf 2)"
+		RED="${BOLD}$(tput setaf 1)"
+		YELLOW="${BOLD}$(tput setaf 3)"
+	else
+		ALL_OFF="\e[1;0m"
+		BOLD="\e[1;1m"
+		BLUE="${BOLD}\e[1;34m"
+		GREEN="${BOLD}\e[1;32m"
+		RED="${BOLD}\e[1;31m"
+		YELLOW="${BOLD}\e[1;33m"
+	fi
+fi
+readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
+
+plain() {
+	local mesg=$1; shift
+	printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+msg() {
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+msg2() {
+	local mesg=$1; shift
+	printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+warning() {
+	local mesg=$1; shift
+	printf "${YELLOW}==> WARNING:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+error() {
+	local mesg=$1; shift
+	printf "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+exit_error() {
+	error "$1"
+	exit 1
+}
+
+install_arch() {
+	pacman -Qi $1 &> /dev/null
+	if [ $? -ne 0 ]; then
+		msg "Installing package '$1' from arch repository."
+		pacman -S $1
+	else
+		msg "Package '$1' already installed."
+	fi
+}
+
+install_arch starship
+install_arch zsh
+install_arch exa
+install_arch git
+install_arch fzf
+
+msg "Setting required symbolic links."
 ln -sf $(realpath $(dirname "$0"))/zshenv $HOME/.zshenv
 ln -sf $(realpath $(dirname "$0"))/aliases $HOME/.aliases
 ln -sf $(realpath $(dirname "$0"))/profile $HOME/.profile
+
+msg2 "Done."
